name: Unity

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: false
          dotnet: false
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - uses: actions/cache@v4
        with:
          path: coffee-show-up/Library
          key: Library-${{ hashFiles('coffee-show-up/Assets/**', 'coffee-show-up/Packages/**', 'coffee-show-up/ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          customImage: 'unityci/editor:ubuntu-6000.0.26f1-android-3'
          targetPlatform: Android
          projectPath: coffee-show-up
          buildsPath: coffee-show-up/build

      - uses: actions/upload-artifact@v4
        with:
          name: Android.apk
          path: coffee-show-up/build/Android/Android.apk

      - name: Creat a comment on PR
        uses: actions/github-script@v7
        if: ${{ github.event_name == 'pull_request' }}
        with:
          github-token: ${{ secrets.UNITY_PAT }}
          script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `🚀 Android APK available at: ${ context.payload.repository.html_url }/actions/runs/${ context.runId }`
              })

      # Create a tag and release
      - uses: rickstaa/action-create-tag@v1
        if: github.event_name == 'push'
        with:
          tag: apk-${{ github.run_number }}
          tag_exists_error: false
          message: Built apk from continuous integration
      - uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          tag_name: apk-${{ github.run_number }}
          files: coffee-show-up/build/Android/Android.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
